#ifndef BIOBLOCKSEXECUTION_GLOBAL_H
#define BIOBLOCKSEXECUTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BIOBLOCKSEXECUTION_LIBRARY)
#  define BIOBLOCKSEXECUTIONSHARED_EXPORT Q_DECL_EXPORT
#  define MACHINEFLOWSTRINGADAPTER_EXPORT Q_DECL_EXPORT
#else
#  define BIOBLOCKSEXECUTIONSHARED_EXPORT Q_DECL_IMPORT
#  define MACHINEFLOWSTRINGADAPTER_EXPORT Q_DECL_IMPORT
#endif

#endif // BIOBLOCKSEXECUTION_GLOBAL_H
